### ISSUE TITLE
repo sync problem

### ISSUE THREAD

**Issue by hpcfapix** [baylibre-acme/ACME#1]
Hello,

I am trying to checkout the source but came across this problem during "repo sync", the error is showed as follows:

~/acme-bsp$ repo sync
Fetching project meta-baylibre
Permission denied (publickey).
Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
Warning: Permanently added the RSA host key for IP address '192.30.253.112' to the list of known hosts.
Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
error: Cannot fetch meta-baylibre

error: Exited sync due to fetch errors

I use Ubuntu 14.04. Could you help me with this?

Best regards,
Fangli

**Comment by superna9999** [comment]
Hello,

It' s a known issue, the urls in the repo manifest are prefixed with the ssh protocol using the Github account ssh key.

Please try the "next" branch were it has been fixed, along other new features : https://github.com/baylibre-acme/ACME/tree/next

Regards,
Neil

**Comment by hpcfapix** [comment]
Hello,

Thank you very much for your reply.

I am now able to fetch the repo, but when I am trying to build the image with the "make" command, it fails during the following command:

$ source poky/oe-init-build-env && ../poky/scripts/wic create ../meta-baylibre/sdimage-bootpart.wks -e baylibre-acme-image -o /home/fangli/Movidius/acme-bsp/build

The error message is like the following:

Summary: There were 5 ERROR messages shown, returning a non-zero exit code.

Traceback (most recent call last):
  File "../poky/scripts/wic", line 321, in <module>
    sys.exit(main(sys.argv[1:]))
  File "../poky/scripts/wic", line 316, in main
    return hlp.invoke_subcommand(args, parser, hlp.wic_help_usage, subcommands)
  File "/home/fangli/Movidius/acme-bsp/poky/scripts/lib/wic/help.py", line 95, in invoke_subcommand
    subcommands.get(args[0], subcommand_error)[0](args[1:], usage)
  File "../poky/scripts/wic", line 222, in wic_create_subcommand
    if not os.path.isdir(rootfs_dir):
  File "/usr/lib/python2.7/genericpath.py", line 41, in isdir
    st = os.stat(s)
TypeError: coercing to Unicode: need string or buffer, NoneType found

I don't know if the arguments I give are correct as it seems that the rootfs_dir is None, which causing the problem.

Besides, if I want to make the toolchain for other software cross compiling, what should I do?

Best regards,
Fangli

----- Original Message -----

**Comment by superna9999** [comment]
Hi,

I will try to track the error, but we did not have this behaviour before, this is a Yocto python tool... I will check the parameters for sure.

In the meantime, can you give me your system setup ? version ? and python version ?

Thanks,
Neil

**Comment by superna9999** [comment]
There is one patch that was not applied in the next branch, can you try it :

baylibre/meta-baylibre@b2e95fff805c077890076ce24202f2f5d42ca657

The wic tool uses the env variable IMAGE_ROOTFS, DEPLOY_DIR_IMAGE and STAGING_DIR_NATIVE to get rootfs_dir, kernel_dir and native_sysroot. forcing bash for the may solve the issue.

Concerning the toolchain, you can run : 

```
$ source poky/oe-init-build-env
$ bitbake meta-toolchain
```

To generate a compatible toolchain, but this is standard Yocto/OpenEmbedded commands.

**Comment by hpcfapix** [comment]
Hi,

I am now working under Ubuntu 14.04.1, arch x86_64 GNU/Linux and python version is 2.7.6

I couldn't execute "source" command in the Makefile so I run the commands manually.

Thanks!

Regards,
Fangli

----- Original Message -----

**Comment by superna9999** [comment]
Hi,
I merged the fix in the main and next branches, simply running:

```
$ repo sync
```

Will update meta-baylibre with the fixed Makefile.

**Comment by superna9999** [comment]
Hi,

You can test the b1 release you can find here:
https://github.com/baylibre-acme/ACME/releases/tag/b1

Neil

**Comment by hpcfapix** [comment]
Hi,

Thanks very much for your help. Sorry there is one more question following. 

As I am trying to use in one application two acme boards with network connection, I want to change the default hostname before building the new image.

I have found this file "~/acme-bsp/meta-baylibre/meta-baylibre-acme/recipes-bsp/u-boot/uEnv.txt" containing a hostname setting:

hostname=baylibre-acme

Is this the only one I need to change?

Best regards,
Fangli

----- Original Message -----

**Comment by superna9999** [comment]
Hi,

Yes this is the line to change, but if you only need to change the hostname between multiple ACME boards, you can simply change this line in the first boot partition of each SD Card.

Note that re-building the entire image is not our target, if you have packages or features missing from the image, we can provide updated images.

Could you clarify your needs ?

Regards,
Neil
